### ISSUE TITLE
Docker image build crashes with the error

### ISSUE THREAD

**Issue by Bato** [Actyx/DemoMachineKit#13]
I am trying to create the docker image for the Wago Connector app from advanced tutorial.

```
cd DemoMachineKit
npm run node:wago-connector:docker:build-amd64
``` 

The build process aborts with error message: 

``` 
Step 1/9 : FROM node:10-alpine as build
 ---> b328632eb00c
Step 2/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 5b881408aef5
Step 3/9 : RUN apk add --update gcc g++ libc-dev python3 make
 ---> Running in 031fe7601bd2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
``` 

Solution was to build docker image with flag "--network host" 
Here is the changed line in DemoMachineKit/package.json

./DemoMachineKit/package.json

"node:wago-connector:docker:build-amd64": "npm run node:wago-connector:build && docker build --network host -t wago-connector-amd64 -f src/wago-connector/Dockerfile .",

My configuration is 
- Ubuntu: 18.04
- npm: 6.14.8
- Docker version 19.03.6,
- Advanced Tutorial: https://developer.actyx.com/docs/learn-actyx/advanced-tutorial/get-started

**Comment by wngr** [comment]
Hi @Bato,
thanks for your report. I just gave this a spin, and `cd DemoMachineKit && npm i && npm run node:wago-connector:docker:build-amd64` results in a successfully built image for me.

Looking at the error message, it seems that this might be related to your network. Maybe there's an issue resolving `dl-cdn.alpinelinux.org`?

**Comment by Alexander89** [comment]
I had the same issue with my docker installation. The only fix that finally works out for me, was to uninstall docker, remove the config files, remove the docker0 network adapter, and install it again.

 > remove the docker0 network adapter
is very important

**Comment by Bato** [comment]
Thanks for the tips. For me the workaround with `--network host` is sufficient.
I found it important to ask this question in case the other developers get the same problem.
As far as I am concerned, this issue can be closed

**Comment by wngr** [comment]
Thanks for reporting the workaround!
